server:
  port: 9090

spring:
  application:
    name: shareit-server
  datasource:
    url: jdbc:postgresql://localhost:5432/shareit_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always

logging:
  level:
    root: INFO
    org:
      springframework:
        orm:
          jpa: INFO
          jpa.JpaTransactionManager: DEBUG
        transaction: INFO
        transaction.interceptor: TRACE
      hibernate.orm.jdbc.bind: TRACE
    ru.practicum.shareit.server: DEBUG