# Spring Boot Server Configuration
server:
  port: 8080 # Port the gateway will listen on

spring:
  application:
    name: shareit-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true

shareit-server:
  url: http://server:9090

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
    ru.practicum.shareit.gateway: DEBUG